// Run: npm run test:agents
import { test } from "node:test";
import assert from "node:assert/strict";
import { buildAdapters, parseFrontmatter, renderFrontmatter, validateRole, validateSkill } from "./agents-sync.mjs";

const skillText = (extra = "", body = "Do the thing.") =>
  `---\nname: verify-change\ndescription: Checks a change.\n${extra}---\n\n${body}\n`;

test("parses the frontmatter subset the neutral files use", () => {
  const { data, body } = parseFrontmatter(
    "---\nname: a\ncapabilities: [read, edit]\nowns:\n  - \"src/lib/**\"\nmetadata:\n  version: \"1\"\n---\nBody\n",
  );
  assert.deepEqual(data, { name: "a", capabilities: ["read", "edit"], owns: ["src/lib/**"], metadata: { version: "1" } });
  assert.equal(body, "Body\n");
});

test("frontmatter survives a render and re-parse unchanged", () => {
  const data = { name: "verify-change", description: "Runs checks: lint, types.", metadata: { version: "1" } };
  assert.deepEqual(parseFrontmatter(renderFrontmatter(data) + "x").data, data);
});

test("accepts a skill that uses only Agent Skills standard fields", () => {
  const errors = [];
  validateSkill("verify-change", skillText("license: Proprietary\n"), "SKILL.md", errors);
  assert.deepEqual(errors, []);
});

test("rejects tool-specific skill fields, a name/folder mismatch and model ids", () => {
  const errors = [];
  validateSkill("other-name", skillText("model: opus\ncontext: fork\n", "Use claude-opus-5 for this."), "SKILL.md", errors);
  assert.ok(errors.some((e) => e.includes('"model" is not an Agent Skills standard field')));
  assert.ok(errors.some((e) => e.includes('"context" is not')));
  assert.ok(errors.some((e) => e.includes("must match its folder")));
  assert.ok(errors.some((e) => e.includes("provider model id")));
});

test("rejects a role with a model instead of a tier, or an unknown capability", () => {
  const errors = [];
  const tiers = { deep: {}, standard: {}, fast: {} };
  validateRole("r.md", "---\nname: r\ndescription: d\nmodel: sonnet\ncapabilities: [read, teleport]\n---\n", "r.md", errors, tiers);
  assert.ok(errors.some((e) => e.includes('unknown role field "model"')));
  assert.ok(errors.some((e) => e.includes("tier must be one of")));
  assert.ok(errors.some((e) => e.includes('unknown capability "teleport"')));
});

test("generates Claude and Gemini adapters from one policy, with the same guard", () => {
  const policy = {
    hook: "scripts/agent-guards/hook.mjs",
    deny: { read: [".env.local"], write: [".env.local"], shell: ["gh pr merge"] },
    ask: { shell: ["git push"] },
    allow: { shell: ["npm test"] },
  };
  const mcp = { servers: { tracker: { command: "node", args: ["tools/tracker.mjs"] }, docs: { url: "https://example.com/mcp" } } };
  const skill = { name: "verify-change", files: new Map([["SKILL.md", skillText()], ["adapters/claude.json", "{}"]]), adapters: { claude: { "argument-hint": "[base]" } } };
  const files = buildAdapters({ policy, mcp, skills: [skill] });

  const claude = JSON.parse(files.get(".claude/settings.json"));
  assert.deepEqual(claude.permissions.deny, ["Read(./.env.local)", "Edit(./.env.local)", "Bash(gh pr merge*)"]);
  assert.match(claude.hooks.PreToolUse[0].hooks[0].command, /scripts\/agent-guards\/hook\.mjs/);

  const gemini = JSON.parse(files.get(".gemini/settings.json"));
  assert.deepEqual(gemini.context.fileName, ["AGENTS.md"]);
  assert.match(gemini.hooks.BeforeTool[0].hooks[0].command, /scripts\/agent-guards\/hook\.mjs/);
  assert.deepEqual(gemini.mcpServers.docs, { httpUrl: "https://example.com/mcp" });
  assert.deepEqual(JSON.parse(files.get(".mcp.json")).mcpServers.tracker, { type: "stdio", command: "node", args: ["tools/tracker.mjs"] });

  const claudeSkill = files.get(".claude/skills/verify-change/SKILL.md");
  assert.match(claudeSkill, /argument-hint: "\[base\]"/, "claude-only extras are merged into the claude copy");
  assert.match(claudeSkill, /generated by npm run agents:sync/);
  assert.ok(!files.has(".claude/skills/verify-change/adapters/claude.json"), "adapter sidecars are not copied");
});
