// Run: npm run test:agents
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  INDEX_END, buildAdapters, globToRegExp, parseFrontmatter, renderFrontmatter,
  validateRole, validateRule, validateSkill,
} from "./agents-sync.mjs";

const skillText = (extra = "", body = "Do the thing.") =>
  `---\nname: verify-change\ndescription: Checks a change.\n${extra}---\n\n${body}\n`;

test("parses the frontmatter subset the neutral files use", () => {
  const { data, body } = parseFrontmatter(
    "---\nname: a\ncapabilities: [read, edit]\nowns:\n  - \"src/lib/**\"\nmetadata:\n  version: \"1\"\n---\nBody\n",
  );
  assert.deepEqual(data, { name: "a", capabilities: ["read", "edit"], owns: ["src/lib/**"], metadata: { version: "1" } });
  assert.equal(body, "Body\n");
});

test("frontmatter survives a render and re-parse unchanged", () => {
  const data = { name: "verify-change", description: "Runs checks: lint, types.", metadata: { version: "1" } };
  assert.deepEqual(parseFrontmatter(renderFrontmatter(data) + "x").data, data);
});

test("accepts a skill that uses only Agent Skills standard fields", () => {
  const errors = [];
  validateSkill("verify-change", skillText("license: Proprietary\n"), "SKILL.md", errors);
  assert.deepEqual(errors, []);
});

test("rejects tool-specific skill fields, a name/folder mismatch and model ids", () => {
  const errors = [];
  validateSkill("other-name", skillText("model: opus\ncontext: fork\n", "Use claude-opus-5 for this."), "SKILL.md", errors);
  assert.ok(errors.some((e) => e.includes('"model" is not an Agent Skills standard field')));
  assert.ok(errors.some((e) => e.includes('"context" is not')));
  assert.ok(errors.some((e) => e.includes("must match its folder")));
  assert.ok(errors.some((e) => e.includes("provider model id")));
});

test("rejects a role with a model instead of a tier, or an unknown capability", () => {
  const errors = [];
  const tiers = { deep: {}, standard: {}, fast: {} };
  validateRole("r.md", "---\nname: r\ndescription: d\nmodel: sonnet\ncapabilities: [read, teleport]\n---\n", "r.md", errors, tiers);
  assert.ok(errors.some((e) => e.includes('unknown role field "model"')));
  assert.ok(errors.some((e) => e.includes("tier must be one of")));
  assert.ok(errors.some((e) => e.includes('unknown capability "teleport"')));
});

test("generates Claude and Gemini adapters from one policy, with the same guard", () => {
  const policy = {
    hook: "scripts/agent-guards/hook.mjs",
    deny: { read: [".env.local"], write: [".env.local"], shell: ["gh pr merge"] },
    ask: { shell: ["git push"] },
    allow: { shell: ["npm test"] },
  };
  const mcp = { servers: { tracker: { command: "node", args: ["tools/tracker.mjs"] }, docs: { url: "https://example.com/mcp" } } };
  const skill = { name: "verify-change", files: new Map([["SKILL.md", skillText()], ["adapters/claude.json", "{}"]]), adapters: { claude: { "argument-hint": "[base]" } } };
  const files = buildAdapters({ policy, mcp, skills: [skill] });

  const claude = JSON.parse(files.get(".claude/settings.json"));
  assert.deepEqual(claude.permissions.deny, ["Read(./.env.local)", "Edit(./.env.local)", "Bash(gh pr merge*)"]);
  assert.match(claude.hooks.PreToolUse[0].hooks[0].command, /scripts\/agent-guards\/hook\.mjs/);

  const gemini = JSON.parse(files.get(".gemini/settings.json"));
  assert.deepEqual(gemini.context.fileName, ["AGENTS.md"]);
  assert.match(gemini.hooks.BeforeTool[0].hooks[0].command, /scripts\/agent-guards\/hook\.mjs/);
  assert.deepEqual(gemini.mcpServers.docs, { httpUrl: "https://example.com/mcp" });
  assert.deepEqual(JSON.parse(files.get(".mcp.json")).mcpServers.tracker, { type: "stdio", command: "node", args: ["tools/tracker.mjs"] });

  const claudeSkill = files.get(".claude/skills/verify-change/SKILL.md");
  assert.match(claudeSkill, /argument-hint: "\[base\]"/, "claude-only extras are merged into the claude copy");
  assert.match(claudeSkill, /generated by npm run agents:sync/);
  assert.ok(!files.has(".claude/skills/verify-change/adapters/claude.json"), "adapter sidecars are not copied");
});

const ruleText = (globs, body = "Source: `docs/conventions.md` §3.") =>
  `---\nname: money\ndescription: Money rules.\nglobs:\n${globs.map((g) => `  - "${g}"`).join("\n")}\n---\n\n${body}\n`;

test("rule globs match the way rule loaders match paths", () => {
  const re = (g) => globToRegExp(g);
  assert.ok(re("src/app/**/*.tsx").test("src/app/page.tsx"), "** matches zero directories");
  assert.ok(re("src/app/**/*.tsx").test("src/app/book/[bookingId]/page.tsx"));
  assert.ok(!re("src/app/**/*.tsx").test("src/app/globals.css"));
  assert.ok(re("src/components/**").test("src/components/map-style.ts"));
  assert.ok(re("src/lib/{pricing,fees}.ts").test("src/lib/fees.ts"));
  assert.ok(!re("src/lib/{pricing,fees}.ts").test("src/lib/fees.test.ts"));
  assert.ok(!re("src/lib/*.ts").test("src/lib/assistant/intent-schema.ts"), "* stays within a segment");
  assert.ok(re(".agents/**").test(".agents/rules/frontend.md"), "dots are literal");
  assert.ok(!re(".agents/**").test("xagents/rules/frontend.md"));
});

test("accepts a rule whose globs match tracked files and that cites the conventions", () => {
  const errors = [];
  validateRule("money.md", ruleText(["src/lib/pricing.ts"]), "money.md", errors, ["src/lib/pricing.ts"]);
  assert.deepEqual(errors, []);
});

test("rejects a rule with a dead glob, no conventions citation, or a mismatched file name", () => {
  const errors = [];
  validateRule("cash.md", ruleText(["src/lib/pricnig.ts"], "Be careful with money."), "cash.md", errors, ["src/lib/pricing.ts"]);
  assert.ok(errors.some((e) => e.includes('glob "src/lib/pricnig.ts" matches no tracked file')));
  assert.ok(errors.some((e) => e.includes("cite the docs/conventions.md section")));
  assert.ok(errors.some((e) => e.includes("must match the file name")));
});

test("generates Claude path-scoped rules and the AGENTS.md index for every other tool", () => {
  const policy = { hook: "h.mjs", deny: { read: [], write: [], shell: [] }, ask: { shell: [] }, allow: { shell: [] } };
  const rule = parseFrontmatter(ruleText(["src/lib/{pricing,fees}.ts", "src/app/book/**"]));
  const agentsMd = `# Title\n\n<!-- BEGIN:agents-rules-index (old) -->\nstale\n${INDEX_END}\n\n# After\n`;
  const files = buildAdapters({ policy, mcp: { servers: {} }, skills: [], rules: [rule], agentsMd });

  const claudeRule = files.get(".claude/rules/money.md");
  assert.deepEqual(parseFrontmatter(claudeRule).data, { paths: ["src/lib/{pricing,fees}.ts", "src/app/book/**"] });
  assert.match(claudeRule, /§3/);

  const md = files.get("AGENTS.md");
  assert.match(md, /\| money \| `src\/lib\/\{pricing,fees\}\.ts`<br>`src\/app\/book\/\*\*` \|/);
  assert.ok(!md.includes("stale"), "the old block is replaced");
  assert.ok(md.startsWith("# Title") && md.trimEnd().endsWith("# After"), "text outside the block is untouched");
});

test("refuses to guess where the index goes when AGENTS.md lost its markers", () => {
  const policy = { hook: "h.mjs", deny: { read: [], write: [], shell: [] }, ask: { shell: [] }, allow: { shell: [] } };
  assert.throws(() => buildAdapters({ policy, mcp: { servers: {} }, skills: [], rules: [], agentsMd: "# no markers\n" }), /markers/);
});

// --- roles -----------------------------------------------------------------
import { toolsFor } from "./agents-sync.mjs";

const tiers = { deep: { claude: "opus", gemini: "pro" }, standard: { claude: "sonnet", gemini: "gemini-9-pro-exact" }, fast: {} };
const roleText = (fm) => `---\n${fm}\n---\n\n## Mission\nDo the work.\n`;

test("a role must declare what it may edit when it can edit, and only then", () => {
  const errors = [];
  validateRole("a.md", roleText("name: a\ndescription: d\ntier: standard\ncapabilities: [read, edit]"), "a.md", errors, tiers);
  validateRole("b.md", roleText("name: b\ndescription: d\ntier: standard\ncapabilities: [read]\nowns:\n  - \"src/**\""), "b.md", errors, tiers);
  assert.ok(errors.some((e) => e.startsWith("a.md") && e.includes("must declare owns")));
  assert.ok(errors.some((e) => e.startsWith("b.md") && e.includes("no edit capability")));
});

test("a role may only reference skills that exist", () => {
  const errors = [];
  validateRole("a.md", roleText("name: a\ndescription: d\ntier: fast\ncapabilities: [read]\nskills: [verify-change, telepathy]"), "a.md", errors, tiers, ["verify-change"]);
  assert.deepEqual(errors, ['a.md: skill "telepathy" does not exist in .agents/skills']);
});

test("capabilities map to each tool's own tool names", () => {
  assert.deepEqual(toolsFor("claude", ["read", "shell", "mcp:playwright"]), ["Read", "Grep", "Glob", "Bash", "PowerShell", "mcp__playwright"]);
  assert.deepEqual(toolsFor("gemini", ["edit", "mcp:playwright"]), ["write_file", "replace", "mcp_playwright_*"]);
});

test("generates Claude and Gemini subagents with tier models and a role-scoped guard", () => {
  const policy = { hook: "scripts/agent-guards/hook.mjs", deny: { read: [], write: [], shell: [] }, ask: { shell: [] }, allow: { shell: [] } };
  const role = parseFrontmatter(roleText('name: backend-engineer\ndescription: "Server work: rules, stores."\ntier: deep\ncapabilities: [read, edit, shell]\nskills: [verify-change]\nowns:\n  - "src/lib/**"'));
  const files = buildAdapters({ policy, mcp: { servers: {} }, skills: [], roles: [role], models: { tiers } });

  const claude = files.get(".claude/agents/backend-engineer.md");
  const c = parseFrontmatter(claude.replace(/\nhooks:[\s\S]*?\n---/, "\n---")).data;
  assert.equal(c.model, "opus");
  assert.equal(c.tools, "Read, Grep, Glob, Edit, Write, Bash, PowerShell");
  assert.deepEqual(c.skills, ["verify-change"]);
  assert.match(claude, /hook\.mjs\\" --role backend-engineer"/, "the per-agent hook passes the role");
  assert.match(claude, /You may edit only: `src\/lib\/\*\*`/);

  const gemini = parseFrontmatter(files.get(".gemini/agents/backend-engineer.md")).data;
  assert.equal(gemini.model, "inherit", "tier aliases are not exact Gemini model ids");
  assert.equal(gemini.kind, "local");
  assert.ok(gemini.tools.includes("run_shell_command"));

  const std = parseFrontmatter(roleText("name: x\ndescription: d\ntier: standard\ncapabilities: [read]"));
  assert.equal(parseFrontmatter(buildAdapters({ policy, mcp: { servers: {} }, skills: [], roles: [std], models: { tiers } }).get(".gemini/agents/x.md")).data.model,
    "gemini-9-pro-exact", "an exact model id in models.json is used as is");
});
